name = "azeta-homes"
compatibility_date = "2024-03-27"
workers_dev = true

[assets]
directory = "dist"

[build]
command = "npm run build"

[[routes]]
pattern = "argeniszabala.com"
custom_domain = true
