/**
 * seed-admin.ts
 *
 * Generates a hashed password + salt for the admin user using Web Crypto API
 * (PBKDF2 with SHA-256), then outputs the SQL INSERT statement.
 *
 * Usage:
 *   npx tsx scripts/seed-admin.ts [password]
 *
 * If no password argument is provided, it defaults to a random 24-char password
 * and prints it to stderr so you can save it.
 */

const ITERATIONS = 100_000;
const KEY_LENGTH = 32; // bytes (256 bits)

function toHex(buffer: ArrayBuffer): string {
  return [...new Uint8Array(buffer)]
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

async function generateSalt(): Promise<string> {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  return toHex(bytes.buffer);
}

async function hashPassword(password: string, salt: string): Promise<string> {
  const encoder = new TextEncoder();

  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(password),
    'PBKDF2',
    false,
    ['deriveBits'],
  );

  const derivedBits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      salt: encoder.encode(salt),
      iterations: ITERATIONS,
      hash: 'SHA-256',
    },
    keyMaterial,
    KEY_LENGTH * 8,
  );

  return toHex(derivedBits);
}

function generateRandomPassword(length = 24): string {
  const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*';
  const values = crypto.getRandomValues(new Uint8Array(length));
  return Array.from(values, (v) => charset[v % charset.length]).join('');
}

function escapeSql(value: string): string {
  return value.replace(/'/g, "''");
}

async function main() {
  const password = process.argv[2] || generateRandomPassword();

  if (!process.argv[2]) {
    console.error(`No password provided. Generated random password:\n  ${password}\n`);
    console.error('Save this password somewhere safe -- it cannot be recovered.\n');
  }

  const salt = await generateSalt();
  const passwordHash = await hashPassword(password, salt);

  const sql = `-- Admin user seed (generated by seed-admin.ts)
-- Algorithm: PBKDF2-SHA256, ${ITERATIONS.toLocaleString()} iterations, ${KEY_LENGTH * 8}-bit key

INSERT OR REPLACE INTO admin_users (email, password_hash, salt, role, is_active)
VALUES (
    'admin@azetahomes.com',
    '${escapeSql(passwordHash)}',
    '${escapeSql(salt)}',
    'super_admin',
    1
);`;

  console.log(sql);
}

main().catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
